import { dark } from "react-syntax-highlighter/dist/esm/styles/hljs";

// src/constants/colors.ts
export const lightColors = {

  // header color and statusbar color in light mode
  headerColor: '#1E88E5',
  secondHeaderColor: '#42A5F5',
  thirdHeaderColor: '#FFFFFF',
  statusBarColor: '#1E88E5',
  resetCodeColor: '#FFFFFF',
  backgroundColor: '#FFFFFF',
  bookmarkBatchColor: '#F5F5F5',
  textPrimaryColor: '#3d4149',
  shareButtonColor: '#F5F5F5',
  textSecondaryColor: '#4b5563',
  themeToggleColor: '#1E88E5',
  textSecondaryLightColor: '#455A64',
  searchBarIconColor: '#455A64',
  searchBarTextColor: '#455A64',
  borderColor: '#e5e7eb',
  primaryColor: '#1E88E5',
  primaryLightColor: '#42A5F5',
  secondaryColor: '#42A5F5',
  dangerColor: '#EF4444',
  successColor: '#22c55e',
  warningColor: '#F59E0B',
  mutedColor: '#9CA3AF',
  bottomTabIconColor: '#90A4AE',
  rippleColor: '#ECEFF1',
  codeEditorBackgroundColor: '#f5f5f5',
  codeEditorLineNumberColor: '#e0e0e0',
  codeEditorNumberLineTextColor: '#94a3b8',
  codeEditorTextColor: '#000000',
  codeEditorPlaceholderColor: '#94a3b8',
  codeEditorGutterColor: '#eeeeee',
  codeEditorCursorColor: '#3d4149',
  codeEditorSelectedTextColor: '#3d4149',
  codeEditorSelectedBackgroundColor: '#e0e0e0',
  codeEditorLineHighlightColor: '#f0f0f0',
  codeEditorCursorGuideColor: '#e0e0e0',
  codeEditorBracketColor: '#3d4149',
};

export const darkColors = {
  // header color and statusbar color in dark mode
  headerColor: '#272F3B',
  secondHeaderColor: '#272F3B',
  thirdHeaderColor: '#272F3B',
  statusBarColor: '#272F3B',
  bookmarkBatchColor: '#F5F5F5',
  shareButtonColor: '#F5F5F5',
  backgroundColor: '#272F3B',
  textPrimaryColor: '#FFFFFF',
  themeToggleColor: '#94A3B8',
  resetCodeColor: '#FFFFFF',
  textSecondaryColor: '#CBD5E1',
  textSecondaryLightColor: '#94A3B8',
  borderColor: '#374151',
  searchBarIconColor: '#CBD5E1',
  searchBarTextColor: '#CBD5E1',
  primaryColor: '#1E88E5',
  primaryLightColor: '#42A5F5',
  secondaryColor: '#22D3EE',
  dangerColor: '#EF4444',
  successColor: '#22c55e',
  warningColor: '#F59E0B',
  mutedColor: '#6B7280',
  bottomTabIconColor: '#90A4AE',
  rippleColor: '#374151',
  codeEditorBackgroundColor: '#212731',
  codeEditorLineNumberColor: '#363f4f',
  codeEditorNumberLineTextColor: '#94a3b8',
  codeEditorTextColor: '#F8F8F2',
  codeEditorPlaceholderColor: '#94a3b8',
  codeEditorGutterColor: '#171b22',
  codeEditorCursorColor: '#F8F8F2',
  codeEditorSelectedTextColor: '#F8F8F2',
  codeEditorSelectedBackgroundColor: '#3B4048',
  codeEditorLineHighlightColor: '#3B4048',
  codeEditorCursorGuideColor: '#3B4048',
  codeEditorBracketColor: '#F8F8F2',
};
